<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AdvVoyage extends \App\Entity\AdvVoyage implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'AdvPays' => [parent::class, 'AdvPays', null],
        "\0".parent::class."\0".'Date_depart' => [parent::class, 'Date_depart', null],
        "\0".parent::class."\0".'Date_fin' => [parent::class, 'Date_fin', null],
        "\0".parent::class."\0".'Duree' => [parent::class, 'Duree', null],
        "\0".parent::class."\0".'Nombre_pers_max' => [parent::class, 'Nombre_pers_max', null],
        "\0".parent::class."\0".'Nombre_pers_min' => [parent::class, 'Nombre_pers_min', null],
        "\0".parent::class."\0".'Prix' => [parent::class, 'Prix', null],
        "\0".parent::class."\0".'Resume' => [parent::class, 'Resume', null],
        "\0".parent::class."\0".'Url_image' => [parent::class, 'Url_image', null],
        "\0".parent::class."\0".'advCategorie' => [parent::class, 'advCategorie', null],
        "\0".parent::class."\0".'advReservation' => [parent::class, 'advReservation', null],
        "\0".parent::class."\0".'advUser' => [parent::class, 'advUser', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'AdvPays' => [parent::class, 'AdvPays', null],
        'Date_depart' => [parent::class, 'Date_depart', null],
        'Date_fin' => [parent::class, 'Date_fin', null],
        'Duree' => [parent::class, 'Duree', null],
        'Nombre_pers_max' => [parent::class, 'Nombre_pers_max', null],
        'Nombre_pers_min' => [parent::class, 'Nombre_pers_min', null],
        'Prix' => [parent::class, 'Prix', null],
        'Resume' => [parent::class, 'Resume', null],
        'Url_image' => [parent::class, 'Url_image', null],
        'advCategorie' => [parent::class, 'advCategorie', null],
        'advReservation' => [parent::class, 'advReservation', null],
        'advUser' => [parent::class, 'advUser', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
