<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AdvUser extends \App\Entity\AdvUser implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Mail' => [parent::class, 'Mail', null],
        "\0".parent::class."\0".'Mdp' => [parent::class, 'Mdp', null],
        "\0".parent::class."\0".'Nom' => [parent::class, 'Nom', null],
        "\0".parent::class."\0".'Prénom' => [parent::class, 'Prénom', null],
        "\0".parent::class."\0".'Téléphone' => [parent::class, 'Téléphone', null],
        "\0".parent::class."\0".'advReservation' => [parent::class, 'advReservation', null],
        "\0".parent::class."\0".'advRole' => [parent::class, 'advRole', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Mail' => [parent::class, 'Mail', null],
        'Mdp' => [parent::class, 'Mdp', null],
        'Nom' => [parent::class, 'Nom', null],
        'Prénom' => [parent::class, 'Prénom', null],
        'Téléphone' => [parent::class, 'Téléphone', null],
        'advReservation' => [parent::class, 'advReservation', null],
        'advRole' => [parent::class, 'advRole', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
