<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__AdvReservation__CLASSMETADATA__' => 0,
'App__Entity__AdvUser__CLASSMETADATA__' => 1,
'App__Entity__AdvVoyage__CLASSMETADATA__' => 2,
'App__Entity__AdvCategorie__CLASSMETADATA__' => 3,
'App__Entity__AdvPays__CLASSMETADATA__' => 4,
'App__Entity__AdvRole__CLASSMETADATA__' => 5,
'App__Entity__AdvStatut__CLASSMETADATA__' => 6,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvReservation',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvReservationRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Message' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'message' => 'Message',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Message' => 'message',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_reservation',
                    ],
                ],
                'associationMappings' => [
                    [
                        'advVoyage' => $o[3],
                        'advUser' => $o[5],
                        'advStatut' => $o[7],
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\AdvReservation',
                    4 => 'adv_voyage_id',
                    6 => 'adv_user_id',
                    8 => 'adv_statut_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Message',
                ],
                'columnName' => [
                    1 => 'id',
                    'message',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                    5 => 2,
                    7 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\AdvReservation',
                    5 => 'App\\Entity\\AdvReservation',
                    7 => 'App\\Entity\\AdvReservation',
                ],
                'inversedBy' => [
                    3 => 'AdvReservation',
                    5 => 'AdvReservation',
                    7 => 'AdvReservations',
                ],
                'sourceToTargetKeyColumns' => [
                    3 => [
                        'adv_voyage_id' => 'id',
                    ],
                    5 => [
                        'adv_user_id' => 'id',
                    ],
                    7 => [
                        'adv_statut_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    3 => [
                        'id' => 'adv_voyage_id',
                    ],
                    5 => [
                        'id' => 'adv_user_id',
                    ],
                    7 => [
                        'id' => 'adv_statut_id',
                    ],
                ],
                'joinColumns' => [
                    3 => [
                        $o[4],
                    ],
                    5 => [
                        $o[6],
                    ],
                    7 => [
                        $o[8],
                    ],
                ],
                'joinColumnFieldNames' => [
                    3 => [
                        'adv_voyage_id' => 'adv_voyage_id',
                    ],
                    5 => [
                        'adv_user_id' => 'adv_user_id',
                    ],
                    7 => [
                        'adv_statut_id' => 'adv_statut_id',
                    ],
                ],
                'referencedColumnName' => [
                    4 => 'id',
                    6 => 'id',
                    8 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'advVoyage',
                    5 => 'advUser',
                    7 => 'advStatut',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AdvVoyage',
                    5 => 'App\\Entity\\AdvUser',
                    7 => 'App\\Entity\\advStatut',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvUser',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvUserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nom' => $o[2],
                        'Prénom' => $o[3],
                        'Mail' => $o[4],
                        'Téléphone' => $o[5],
                        'Mdp' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                        'prénom' => 'Prénom',
                        'mail' => 'Mail',
                        'téléphone' => 'Téléphone',
                        'mdp' => 'Mdp',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                        'Prénom' => 'prénom',
                        'Mail' => 'mail',
                        'Téléphone' => 'téléphone',
                        'Mdp' => 'mdp',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_user',
                    ],
                ],
                'associationMappings' => [
                    [
                        'advReservation' => $o[7],
                        'advRole' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[10],
                ],
                'name' => [
                    'App\\Entity\\AdvUser',
                    9 => 'adv_role_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nom',
                    'Prénom',
                    'Mail',
                    'Téléphone',
                    'Mdp',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                    'prénom',
                    'mail',
                    'téléphone',
                    'mdp',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    15,
                    255,
                ],
                'fetch' => [
                    7 => 2,
                    2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\AdvUser',
                    'App\\Entity\\AdvUser',
                ],
                'mappedBy' => [
                    7 => 'advUser',
                ],
                'inversedBy' => [
                    8 => 'advUsers',
                ],
                'sourceToTargetKeyColumns' => [
                    8 => [
                        'adv_role_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    8 => [
                        'id' => 'adv_role_id',
                    ],
                ],
                'joinColumns' => [
                    8 => [
                        $o[9],
                    ],
                ],
                'joinColumnFieldNames' => [
                    8 => [
                        'adv_role_id' => 'adv_role_id',
                    ],
                ],
                'referencedColumnName' => [
                    9 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'advReservation',
                    'advRole',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\advReservation',
                    'App\\Entity\\advRole',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinTableMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvVoyage',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvVoyageRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Duree' => $o[2],
                        'Date_depart' => $o[3],
                        'Date_fin' => $o[4],
                        'Url_image' => $o[5],
                        'Resume' => $o[6],
                        'Nombre_pers_min' => $o[7],
                        'Nombre_pers_max' => $o[8],
                        'Prix' => $o[9],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'duree' => 'Duree',
                        'date_depart' => 'Date_depart',
                        'date_fin' => 'Date_fin',
                        'url_image' => 'Url_image',
                        'resume' => 'Resume',
                        'nombre_pers_min' => 'Nombre_pers_min',
                        'nombre_pers_max' => 'Nombre_pers_max',
                        'prix' => 'Prix',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Duree' => 'duree',
                        'Date_depart' => 'date_depart',
                        'Date_fin' => 'date_fin',
                        'Url_image' => 'url_image',
                        'Resume' => 'resume',
                        'Nombre_pers_min' => 'nombre_pers_min',
                        'Nombre_pers_max' => 'nombre_pers_max',
                        'Prix' => 'prix',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_voyage',
                    ],
                ],
                'associationMappings' => [
                    [
                        'AdvPays' => $o[10],
                        'advCategorie' => $o[14],
                        'advUser' => $o[18],
                        'advReservation' => $o[20],
                    ],
                ],
                'idGenerator' => [
                    $o[21],
                ],
                'name' => [
                    'App\\Entity\\AdvVoyage',
                    11 => 'adv_voyage_adv_pays',
                    'adv_voyage_id',
                    'adv_pays_id',
                    15 => 'adv_voyage_adv_categorie',
                    'adv_voyage_id',
                    'adv_categorie_id',
                    19 => 'adv_user_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'datetime',
                    'datetime',
                    'string',
                    'string',
                    'integer',
                    'integer',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Duree',
                    'Date_depart',
                    'Date_fin',
                    'Url_image',
                    'Resume',
                    'Nombre_pers_min',
                    'Nombre_pers_max',
                    'Prix',
                ],
                'columnName' => [
                    1 => 'id',
                    'duree',
                    'date_depart',
                    'date_fin',
                    'url_image',
                    'resume',
                    'nombre_pers_min',
                    'nombre_pers_max',
                    'prix',
                ],
                'length' => [
                    5 => 255,
                    255,
                ],
                'fetch' => [
                    10 => 2,
                    14 => 2,
                    18 => 2,
                    20 => 2,
                ],
                'isOnDeleteCascade' => [
                    10 => true,
                    14 => true,
                ],
                'sourceEntity' => [
                    10 => 'App\\Entity\\AdvVoyage',
                    14 => 'App\\Entity\\AdvVoyage',
                    18 => 'App\\Entity\\AdvVoyage',
                    20 => 'App\\Entity\\AdvVoyage',
                ],
                'inversedBy' => [
                    10 => 'advVoyages',
                    14 => 'advVoyages',
                ],
                'joinTable' => [
                    10 => $o[11],
                    14 => $o[15],
                ],
                'joinTableColumns' => [
                    10 => [
                        'adv_voyage_id',
                        'adv_pays_id',
                    ],
                    14 => [
                        'adv_voyage_id',
                        'adv_categorie_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    10 => [
                        'adv_voyage_id' => 'id',
                    ],
                    14 => [
                        'adv_voyage_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    10 => [
                        'adv_pays_id' => 'id',
                    ],
                    14 => [
                        'adv_categorie_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    11 => [
                        $o[12],
                    ],
                    15 => [
                        $o[16],
                    ],
                    18 => [
                        $o[19],
                    ],
                ],
                'inverseJoinColumns' => [
                    11 => [
                        $o[13],
                    ],
                    15 => [
                        $o[17],
                    ],
                ],
                'onDelete' => [
                    12 => 'CASCADE',
                    'CASCADE',
                    16 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    12 => 'id',
                    'id',
                    16 => 'id',
                    'id',
                    19 => 'id',
                ],
                'sourceToTargetKeyColumns' => [
                    18 => [
                        'adv_user_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    18 => [
                        'id' => 'adv_user_id',
                    ],
                ],
                'joinColumnFieldNames' => [
                    18 => [
                        'adv_user_id' => 'adv_user_id',
                    ],
                ],
                'mappedBy' => [
                    20 => 'advVoyage',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    10 => 'AdvPays',
                    14 => 'advCategorie',
                    18 => 'advUser',
                    20 => 'advReservation',
                ],
                'targetEntity' => [
                    10 => 'App\\Entity\\AdvPays',
                    14 => 'App\\Entity\\advCategorie',
                    18 => 'App\\Entity\\advUser',
                    20 => 'App\\Entity\\advReservation',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvCategorie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvCategorieRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nom' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_categorie',
                    ],
                ],
                'associationMappings' => [
                    [
                        'advVoyages' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\AdvCategorie',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nom',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\AdvCategorie',
                ],
                'mappedBy' => [
                    3 => 'advCategorie',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'advVoyages',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AdvVoyage',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvPays',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvPaysRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nom' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_pays',
                    ],
                ],
                'associationMappings' => [
                    [
                        'advVoyages' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\AdvPays',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nom',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\AdvPays',
                ],
                'mappedBy' => [
                    3 => 'AdvPays',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'advVoyages',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AdvVoyage',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvRole',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvRoleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nom' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_role',
                    ],
                ],
                'associationMappings' => [
                    [
                        'advUsers' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\AdvRole',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nom',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\AdvRole',
                ],
                'mappedBy' => [
                    3 => 'AdvRole',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'advUsers',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AdvUser',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\AdvStatut',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AdvStatutRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nom' => $o[2],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'adv_statut',
                    ],
                ],
                'associationMappings' => [
                    [
                        'advReservations' => $o[3],
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\AdvStatut',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nom',
                ],
                'columnName' => [
                    1 => 'id',
                    'nom',
                ],
                'length' => [
                    2 => 255,
                ],
                'fetch' => [
                    3 => 2,
                ],
                'sourceEntity' => [
                    3 => 'App\\Entity\\AdvStatut',
                ],
                'mappedBy' => [
                    3 => 'advStatut',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    3 => 'advReservations',
                ],
                'targetEntity' => [
                    3 => 'App\\Entity\\AdvReservation',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
