<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'a7c3ddce4abb5c6b6c86e4aad89e84e5',
  'DATABASE_URL' => 'mysql://adv2:adv2@127.0.0.1:3306/adv2?serverVersion=10.5.23-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
