<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kj7H0RMService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kj7H0RM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kj7H0RM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advVoyageRepository' => ['privates', 'App\\Repository\\AdvVoyageRepository', 'getAdvVoyageRepositoryService', true],
        ], [
            'advVoyageRepository' => 'App\\Repository\\AdvVoyageRepository',
        ]);
    }
}
