<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RGep_WAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rGep.wA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rGep.wA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advVoyage' => ['privates', '.errored..service_locator.rGep.wA.App\\Entity\\AdvVoyage', NULL, 'Cannot autowire service ".service_locator.rGep.wA": it needs an instance of "App\\Entity\\AdvVoyage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'advVoyage' => 'App\\Entity\\AdvVoyage',
        ]);
    }
}
