<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CEbERBkService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.cEbERBk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cEbERBk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advReservation' => ['privates', '.errored..service_locator.cEbERBk.App\\Entity\\AdvReservation', NULL, 'Cannot autowire service ".service_locator.cEbERBk": it needs an instance of "App\\Entity\\AdvReservation" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'advReservation' => 'App\\Entity\\AdvReservation',
            'entityManager' => '?',
        ]);
    }
}
