<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4a0TzDService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._4a0TzD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._4a0TzD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'advReservation' => ['privates', '.errored..service_locator._4a0TzD.App\\Entity\\AdvReservation', NULL, 'Cannot autowire service ".service_locator._4a0TzD": it needs an instance of "App\\Entity\\AdvReservation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'advReservation' => 'App\\Entity\\AdvReservation',
        ]);
    }
}
