<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvUserRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AdvUserRepository' shared autowired service.
     *
     * @return \App\Repository\AdvUserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AdvUserRepository'] = new \App\Repository\AdvUserRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
