<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvReservation2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.cEbERBk.App\Entity\AdvReservation' shared service.
     *
     * @return \App\Entity\AdvReservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cEbERBk": it needs an instance of "App\\Entity\\AdvReservation" but this type has been excluded in "config/services.yaml".');
    }
}
