<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdvReservationController::delete' => ['privates', '.service_locator.cEbERBk', 'get_ServiceLocator_CEbERBkService', true],
            'App\\Controller\\AdvReservationController::edit' => ['privates', '.service_locator.cEbERBk', 'get_ServiceLocator_CEbERBkService', true],
            'App\\Controller\\AdvReservationController::index' => ['privates', '.service_locator.zmUCnzE', 'get_ServiceLocator_ZmUCnzEService', true],
            'App\\Controller\\AdvReservationController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdvReservationController::show' => ['privates', '.service_locator._4a0TzD', 'get_ServiceLocator_4a0TzDService', true],
            'App\\Controller\\AdvUserController::delete' => ['privates', '.service_locator.FJ8V9Iz', 'get_ServiceLocator_FJ8V9IzService', true],
            'App\\Controller\\AdvUserController::edit' => ['privates', '.service_locator.FJ8V9Iz', 'get_ServiceLocator_FJ8V9IzService', true],
            'App\\Controller\\AdvUserController::index' => ['privates', '.service_locator.nKIFnti', 'get_ServiceLocator_NKIFntiService', true],
            'App\\Controller\\AdvUserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdvUserController::show' => ['privates', '.service_locator.7Ojipmz', 'get_ServiceLocator_7OjipmzService', true],
            'App\\Controller\\AdvVoyageController::delete' => ['privates', '.service_locator.FgAs6Wz', 'get_ServiceLocator_FgAs6WzService', true],
            'App\\Controller\\AdvVoyageController::edit' => ['privates', '.service_locator.FgAs6Wz', 'get_ServiceLocator_FgAs6WzService', true],
            'App\\Controller\\AdvVoyageController::index' => ['privates', '.service_locator.kj7H0RM', 'get_ServiceLocator_Kj7H0RMService', true],
            'App\\Controller\\AdvVoyageController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdvVoyageController::show' => ['privates', '.service_locator.rGep.wA', 'get_ServiceLocator_RGep_WAService', true],
            'App\\Controller\\Api\\ReservationController::index' => ['privates', '.service_locator.zmUCnzE', 'get_ServiceLocator_ZmUCnzEService', true],
            'App\\Controller\\Api\\ReservationController::new' => ['privates', '.service_locator.OOnurLL', 'get_ServiceLocator_OOnurLLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdvReservationController:delete' => ['privates', '.service_locator.cEbERBk', 'get_ServiceLocator_CEbERBkService', true],
            'App\\Controller\\AdvReservationController:edit' => ['privates', '.service_locator.cEbERBk', 'get_ServiceLocator_CEbERBkService', true],
            'App\\Controller\\AdvReservationController:index' => ['privates', '.service_locator.zmUCnzE', 'get_ServiceLocator_ZmUCnzEService', true],
            'App\\Controller\\AdvReservationController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdvReservationController:show' => ['privates', '.service_locator._4a0TzD', 'get_ServiceLocator_4a0TzDService', true],
            'App\\Controller\\AdvUserController:delete' => ['privates', '.service_locator.FJ8V9Iz', 'get_ServiceLocator_FJ8V9IzService', true],
            'App\\Controller\\AdvUserController:edit' => ['privates', '.service_locator.FJ8V9Iz', 'get_ServiceLocator_FJ8V9IzService', true],
            'App\\Controller\\AdvUserController:index' => ['privates', '.service_locator.nKIFnti', 'get_ServiceLocator_NKIFntiService', true],
            'App\\Controller\\AdvUserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdvUserController:show' => ['privates', '.service_locator.7Ojipmz', 'get_ServiceLocator_7OjipmzService', true],
            'App\\Controller\\AdvVoyageController:delete' => ['privates', '.service_locator.FgAs6Wz', 'get_ServiceLocator_FgAs6WzService', true],
            'App\\Controller\\AdvVoyageController:edit' => ['privates', '.service_locator.FgAs6Wz', 'get_ServiceLocator_FgAs6WzService', true],
            'App\\Controller\\AdvVoyageController:index' => ['privates', '.service_locator.kj7H0RM', 'get_ServiceLocator_Kj7H0RMService', true],
            'App\\Controller\\AdvVoyageController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdvVoyageController:show' => ['privates', '.service_locator.rGep.wA', 'get_ServiceLocator_RGep_WAService', true],
            'App\\Controller\\Api\\ReservationController:index' => ['privates', '.service_locator.zmUCnzE', 'get_ServiceLocator_ZmUCnzEService', true],
            'App\\Controller\\Api\\ReservationController:new' => ['privates', '.service_locator.OOnurLL', 'get_ServiceLocator_OOnurLLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdvReservationController::delete' => '?',
            'App\\Controller\\AdvReservationController::edit' => '?',
            'App\\Controller\\AdvReservationController::index' => '?',
            'App\\Controller\\AdvReservationController::new' => '?',
            'App\\Controller\\AdvReservationController::show' => '?',
            'App\\Controller\\AdvUserController::delete' => '?',
            'App\\Controller\\AdvUserController::edit' => '?',
            'App\\Controller\\AdvUserController::index' => '?',
            'App\\Controller\\AdvUserController::new' => '?',
            'App\\Controller\\AdvUserController::show' => '?',
            'App\\Controller\\AdvVoyageController::delete' => '?',
            'App\\Controller\\AdvVoyageController::edit' => '?',
            'App\\Controller\\AdvVoyageController::index' => '?',
            'App\\Controller\\AdvVoyageController::new' => '?',
            'App\\Controller\\AdvVoyageController::show' => '?',
            'App\\Controller\\Api\\ReservationController::index' => '?',
            'App\\Controller\\Api\\ReservationController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdvReservationController:delete' => '?',
            'App\\Controller\\AdvReservationController:edit' => '?',
            'App\\Controller\\AdvReservationController:index' => '?',
            'App\\Controller\\AdvReservationController:new' => '?',
            'App\\Controller\\AdvReservationController:show' => '?',
            'App\\Controller\\AdvUserController:delete' => '?',
            'App\\Controller\\AdvUserController:edit' => '?',
            'App\\Controller\\AdvUserController:index' => '?',
            'App\\Controller\\AdvUserController:new' => '?',
            'App\\Controller\\AdvUserController:show' => '?',
            'App\\Controller\\AdvVoyageController:delete' => '?',
            'App\\Controller\\AdvVoyageController:edit' => '?',
            'App\\Controller\\AdvVoyageController:index' => '?',
            'App\\Controller\\AdvVoyageController:new' => '?',
            'App\\Controller\\AdvVoyageController:show' => '?',
            'App\\Controller\\Api\\ReservationController:index' => '?',
            'App\\Controller\\Api\\ReservationController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
