<?php

namespace Container0hxJB92;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoyageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\VoyageController' shared autowired service.
     *
     * @return \App\Controller\Api\VoyageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\VoyageController'] = $instance = new \App\Controller\Api\VoyageController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\Api\\VoyageController', $container));

        return $instance;
    }
}
