<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0hxJB92\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0hxJB92/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container0hxJB92.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container0hxJB92\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container0hxJB92\App_KernelProdContainer([
    'container.build_hash' => '0hxJB92',
    'container.build_id' => '288b0c02',
    'container.build_time' => 1715908311,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0hxJB92');
