<?php

namespace Container8AVGO1X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvUserControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdvUserController' shared autowired service.
     *
     * @return \App\Controller\AdvUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdvUserController'] = $instance = new \App\Controller\AdvUserController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\AdvUserController', $container));

        return $instance;
    }
}
