<?php

namespace Container8AVGO1X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvVoyageService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.FgAs6Wz.App\Entity\AdvVoyage' shared service.
     *
     * @return \App\Entity\AdvVoyage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FgAs6Wz": it needs an instance of "App\\Entity\\AdvVoyage" but this type has been excluded in "config/services.yaml".');
    }
}
