<?php

namespace Container8AVGO1X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvUser2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.FJ8V9Iz.App\Entity\AdvUser' shared service.
     *
     * @return \App\Entity\AdvUser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FJ8V9Iz": it needs an instance of "App\\Entity\\AdvUser" but this type has been excluded in "config/services.yaml".');
    }
}
