<?php

namespace Container8AVGO1X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvVoyageTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AdvVoyageType' shared autowired service.
     *
     * @return \App\Form\AdvVoyageType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AdvVoyageType'] = new \App\Form\AdvVoyageType();
    }
}
